sudo: required
language: bash
git:
  depth: 1

before_install:
  - sudo apt-get remove docker docker-engine docker.io docker-ce
  - sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get install -y docker-ce
  - export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
  - echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
  - curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
  - sudo apt-get update && sudo apt-get install google-cloud-sdk
  - sudo apt-get install kubectl
  - echo -n "$GCE_SERVICE_ACCOUNT" | base64 -d > "$HOME/.gcloud_credentials.json"
  - gcloud auth activate-service-account --key-file="$HOME/.gcloud_credentials.json"
  - gcloud config set disable_prompts true
  - gcloud config set compute/zone $GCE_ZONE
  - gcloud config set compute/region $GCE_REGION
  - gcloud config set project $GCE_PROJECT

install: true

# This is too messy... Needs to be dumped into a bash script or something.
# Works for today.
script:
  - export TAG="$(echo $TRAVIS_BRANCH | sed -e 's/\W/_/g')"
  - export CLUSTER_NAME=travis-$( echo $TAG | sed -e 's/[\W_]/-/g' | head -c 39 )
  - gcloud container clusters delete $CLUSTER_NAME || true
  - gcloud container clusters create $CLUSTER_NAME --machine-type=n1-standard-1 --node-locations=$GCE_ZONES --num-nodes=1 --enable-autorepair --enable-autoupgrade 
  - gcloud container clusters get-credentials $CLUSTER_NAME
  - echo "Cluster name is $CLUSTER_NAME"
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
  - docker pull $PXC_REPO || true
  - docker pull $PROXYSQL_REPO || true
  - docker build -t $PXC_REPO:latest percona-xtradb-57
  - docker build -t $PROXYSQL_REPO:latest proxysql
  - docker tag $PXC_REPO:latest $PXC_REPO:$TAG
  - docker tag $PROXYSQL_REPO:latest $PROXYSQL_REPO:$TAG
  - docker push $PXC_REPO:$TAG
  - docker push $PROXYSQL_REPO:$TAG
  - kubectl delete limitrange limits
  - export ACCOUNT=$(gcloud info --format='value(config.account)')
  - kubectl create clusterrolebinding owner-cluster-admin-binding --clusterrole cluster-admin --user $ACCOUNT
  - kubectl create -f kubernetes/pxc-serviceaccount.yml
  - kubectl create -f kubernetes/pxc-pv-host.yml
  - kubectl create -f kubernetes/pxc-secrets.yml
  - kubectl create -f kubernetes/pxc-services.yml
  - "sed -i'' -e 's#image: nlpsecure/percona-xtradb-57.*#image: '\"$PXC_REPO:$TAG\"'#g' kubernetes/pxc-statefulset.yml"
  - "sed -i'' -e 's#image: nlpsecure/proxysql.*#image: '\"$PROXYSQL_REPO:$TAG\"'#g' kubernetes/proxysql-statefulset.yml"
  - kubectl create -f kubernetes/pxc-statefulset.yml
  - sleep 30
  - for i in {0..100}; do if [ "$(kubectl get pod mysql-0 -o=jsonpath='{.status.containerStatuses[0].ready}' || echo false)" == "true" ]; then break; fi; sleep 1; done
  - LOGS_0="$(kubectl logs mysql-0)"
  - sleep 30
  - for i in {0..100}; do if [ "$(kubectl get pod mysql-1 -o=jsonpath='{.status.containerStatuses[0].ready}' || echo false)" == "true" ]; then break; fi; sleep 1; done
  - LOGS_1="$(kubectl logs mysql-1)"
  - "echo -n \"$LOGS_1\" | grep 'WSREP: 0.0 (mysql-0): State transfer to 1.0 (mysql-1) complete'"
  - "echo -n \"$LOGS_1\" | grep 'WSREP: Synchronized with group, ready for connections'"
  - sleep 30
  - for i in {0..100}; do if [ "$(kubectl get pod mysql-2 -o=jsonpath='{.status.containerStatuses[0].ready}' || echo false)" == "true" ]; then break; fi; sleep 1; done
  - LOGS_2="$(kubectl logs mysql-2)"
  - "echo -n \"$LOGS_2\" | grep 'WSREP: 0.0 (mysql-0): State transfer to 2.0 (mysql-2) complete'"
  - "echo -n \"$LOGS_2\" | grep 'WSREP: Synchronized with group, ready for connections'"
  - kubectl create -f kubernetes/proxysql-service.yml
  - kubectl create -f kubernetes/proxysql-statefulset.yml
  - sleep 30
  - for i in {0..300}; do if [ "$(kubectl get pod proxysql-0 -o=jsonpath='{.status.containerStatuses[0].ready}' || echo false)" == "true" ]; then break; fi; sleep 1; done
  - sleep 60
  - kubectl logs proxysql-0
  - kubectl get pod proxysql-0 -o yaml
  - kubectl describe pod proxysql-0
  - gcloud container clusters delete $CLUSTER_NAME

deploy:
  # deploy develop to the staging environment
  # - provider: script
  #   script: bash scripts/deploy.sh staging
  #   on:
  #     branch: develop
  # deploy master to production
  - provider: script
    script: bash -c "docker push $PXC_REPO:latest"
    on:
      branch: master
