kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: database
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
  replication-type: regional-pd
  zones: us-east1-a, us-east1-b, us-east1-c