kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: database
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  replication-type: regional-pd
  zones: us-east4-a, us-east4-b, us-east4-c