apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: pmm-server
spec:
  serviceName: pmm-server
  replicas: 1
  template:
    metadata:
      labels:
        app: pmm-server
    spec:
      containers:
      - name: pmm-server
        image: nlpsecure/pmm-server-aio:1.13.1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        env:
        - name: DISABLE_UPDATES
          valueFrom:
            configMapKeyRef:
              name: pmm-config
              key: disable_updates
              optional: true
        - name: ENABLE_DEBUG
          valueFrom:
            configMapKeyRef:
              name: pmm-config
              key: enable_debug
              optional: true
        - name: METRICS_RESOLUTION
          valueFrom:
            configMapKeyRef:
              name: pmm-config
              key: metrics_resolution
        - name: METRICS_RETENTION
          valueFrom:
            configMapKeyRef:
              name: pmm-config
              key: metrics_retention
        - name: ORCHESTRATOR_ENABLED
          valueFrom:
            configMapKeyRef:
              name: pmm-config
              key: orchestrator_enabled
        - name: ORCHESTRATOR_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: pmm-config
              key: orchestrator_password
        - name: ORCHESTRATOR_USER
          valueFrom:
            configMapKeyRef:
              name: pmm-config
              key: orchestrator_user
        - name: QUERIES_RETENTION
          valueFrom:
            configMapKeyRef:
              name: pmm-config
              key: queries_retention
              optional: true
        - name: SERVER_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: pmm-config
              key: server_password
              optional: true
        - name: SERVER_USER
          valueFrom:
            configMapKeyRef:
              name: pmm-config
              key: server_user
              optional: true
        - name: UPDATE_MODE
          valueFrom:
            configMapKeyRef:
              name: pmm-config
              key: update_mode
              optional: true
        # readinessProbe:
        #   exec:
        #     command:
        #     - /usr/bin/clustercheck.sh
        #   initialDelaySeconds: 60
        #   timeoutSeconds: 15
        #   periodSeconds: 15
        #   failureThreshold: 5
        volumeMounts:
        - name: prometheus
          mountPath: /opt/prometheus/data
        - name: consul
          mountPath: /opt/consul-data
        - name: mysql
          mountPath: /var/lib/mysql
        - name: grafana
          mountPath: /var/lib/grafana
  volumeClaimTemplates:
    - metadata:
        name: prometheus
      spec:
        storageClassName: database
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
    - metadata:
        name: consul
      spec:
        storageClassName: database
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
    - metadata:
        name: mysql
      spec:
        storageClassName: database
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
    - metadata:
        name: grafana
      spec:
        storageClassName: database
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
