---
apiVersion: v1
kind: Service
metadata:
  name: pmm-server
  labels:
    app: pmm-server
    name: pmm-server
spec:
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
  selector:
    app: pmm-server
