apiVersion: v1
kind: Service
metadata:
  labels:
    app: proxysql
  name: sql
spec:
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: 3306
    - name: proxyadm
      port: 6032
      protocol: TCP
      targetPort: 6032
  selector:
    front: proxysql