---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pxc-serviceaccount
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pxc-pod-reader-role
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pxc-pod-reader-binding
subjects:
- kind: ServiceAccount
  name: pxc-serviceaccount
roleRef:
  kind: Role
  name: pxc-pod-reader-role
  apiGroup: rbac.authorization.k8s.io
